> ["返回值与错误处理"](siyuan://blocks/20221202163333-kxpn8nx)
>
> * ​`Result`​ 用于返回结果处理
> * ​`?`​ 用于错误的传播

## 组合器

> 将对象组合成树形结构以表示“部分整体”的层次结构。组合模式使得用户对单个对象和组合对象的使用具有一致性。–GoF <<设计模式>>

### or() 和 and()

方法对两个表达式做逻辑组合,最终返回`Option/Result`​

* ​`or()`​，表达式按照顺序求值，若任何一个表达式的结果是 `Some`​ 或 `Ok`​，则该值会立刻返回
* ​`and()`​，若两个表达式的结果都是 `Some`​ 或 `Ok`​，则​**第二个表达式中的值被返回**​。若任何一个的结果是 `None`​ 或 `Err`​ ，则立刻返回。

### or_else() 和 and_then()

唯一的区别在于，它们的第二个表达式是一个闭包

```rust
fn main() {
    // or_else with Option
    let s1 = Some("some1");
    let s2 = Some("some2");
    let fn_some = || Some("some2"); // 类似于: let fn_some = || -> Option<&str> { Some("some2") };

    let n: Option<&str> = None;
    let fn_none = || None;

    assert_eq!(s1.or_else(fn_some), s1);  // Some1 or_else Some2 = Some1
    assert_eq!(s1.or_else(fn_none), s1);  // Some or_else None = Some
    assert_eq!(n.or_else(fn_some), s2);   // None or_else Some = Some
    assert_eq!(n.or_else(fn_none), None); // None1 or_else None2 = None2

    // or_else with Result
    let o1: Result<&str, &str> = Ok("ok1");
    let o2: Result<&str, &str> = Ok("ok2");
    let fn_ok = |_| Ok("ok2"); // 类似于: let fn_ok = |_| -> Result<&str, &str> { Ok("ok2") };

    let e1: Result<&str, &str> = Err("error1");
    let e2: Result<&str, &str> = Err("error2");
    let fn_err = |_| Err("error2");

    assert_eq!(o1.or_else(fn_ok), o1);  // Ok1 or_else Ok2 = Ok1
    assert_eq!(o1.or_else(fn_err), o1); // Ok or_else Err = Ok
    assert_eq!(e1.or_else(fn_ok), o2);  // Err or_else Ok = Ok
    assert_eq!(e1.or_else(fn_err), e2); // Err1 or_else Err2 = Err2
}
```

### filter

```rust
fn main() {
    let s1 = Some(3);
    let s2 = Some(6);
    let n = None;

    let fn_is_even = |x: &i8| x % 2 == 0;

    assert_eq!(s1.filter(fn_is_even), n);  // Some(3) -> 3 is not even -> None
    assert_eq!(s2.filter(fn_is_even), s2); // Some(6) -> 6 is even -> Some(6)
    assert_eq!(n.filter(fn_is_even), n);   // None -> no value -> None
}
```

### map() 和 map_err()

将`Some`​或`Ok`​中的值映射为另一个

```rust
fn main() {
    let s1 = Some("abcde");
    let s2 = Some(5);

    let n1: Option<&str> = None;
    let n2: Option<usize> = None;

    let o1: Result<&str, &str> = Ok("abcde");
    let o2: Result<usize, &str> = Ok(5);

    let e1: Result<&str, &str> = Err("abcde");
    let e2: Result<usize, &str> = Err("abcde");

    let fn_character_count = |s: &str| s.chars().count();

    assert_eq!(s1.map(fn_character_count), s2); // Some1 map = Some2
    assert_eq!(n1.map(fn_character_count), n2); // None1 map = None2

    assert_eq!(o1.map(fn_character_count), o2); // Ok1 map = Ok2
    assert_eq!(e1.map(fn_character_count), e2); // Err1 map = Err2
}
```

### map_or() 和 ,map_or_else()

* ​`map_or`​ 在 `map`​ 的基础上提供了一个默认值:

  * ```rust
    fn main() {
        const V_DEFAULT: u32 = 1;

        let s: Result<u32, ()> = Ok(10);
        let n: Option<u32> = None;
        let fn_closure = |v: u32| v + 2;

        assert_eq!(s.map_or(V_DEFAULT, fn_closure), 12);
        // 当处理None时, 默认返回1
        assert_eq!(n.map_or(V_DEFAULT, fn_closure), V_DEFAULT);
    }
    ```
* ​`map_or_else`​ 与 `map_or`​ 类似，但是它是通过一个闭包来提供默认值

  * ```rust
    fn main() {
        let s = Some(10);
        let n: Option<i8> = None;

        let fn_closure = |v: i8| v + 2;
        let fn_default = || 1;

        assert_eq!(s.map_or_else(fn_default, fn_closure), 12);
        assert_eq!(n.map_or_else(fn_default, fn_closure), 1);

        let o = Ok(10);
        let e = Err(5);
        let fn_default_for_result = |v: i8| v + 1; // 闭包可以对 Err 中的值进行处理，并返回一个新值

        assert_eq!(o.map_or_else(fn_default_for_result, fn_closure), 12);
        assert_eq!(e.map_or_else(fn_default_for_result, fn_closure), 6);
    }
    ```

### ok_or() 和 ok_or_else()

将 `Option`​ 类型转换为 `Result`​ 类型

* ​`ok_or`​ 接收一个默认的 `Err`​ 参数
* ​`ok_or_else`​ 接收一个闭包作为 `Err`​ 参数

## 自定义错误类型

```rust
use std::fmt::{Debug, Display};

pub trait Error: Debug + Display {
    fn source(&self) -> Option<&(Error + 'static)> { ... }
}
```

自定义特征实现该特征后,该类型就可作为Err来使用

> 实际上，自定义错误类型只需要实现 `Debug`​ 和 `Display`​ 特征即可，`source`​ 方法是可选的，而 `Debug`​ 特征往往也无需手动实现，可以直接通过 `derive`​ 来派生

### 简单错误示例

```rust
use std::fmt;

// AppError 是自定义错误类型，它可以是当前包中定义的任何类型，在这里为了简化，我们使用了单元结构体作为例子。
// 为 AppError 自动派生 Debug 特征
#[derive(Debug)]
struct AppError;

// 为 AppError 实现 std::fmt::Display 特征
impl fmt::Display for AppError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "An Error Occurred, Please Try Again!") // user-facing output
    }
}

// 一个示例函数用于产生 AppError 错误
fn produce_error() -> Result<(), AppError> {
    Err(AppError)
}

fn main(){
    match produce_error() {
        Err(e) => eprintln!("{}", e),
        _ => println!("No error"),
    }

    eprintln!("{:?}", produce_error()); // Err({ file: src/main.rs, line: 17 })
}
```

* 实现 `Debug`​ 和 `Display`​ 特征并不是作为 `Err`​ 使用的必要条件, 实现原因有

  * 错误得打印输出后，才能有实际用处，而打印输出就需要实现这两个特征
  * 可以将自定义错误转换成 `Box<dyn std::error:Error>`​ 特征对象，在后面的**归一化不同错误类型**部分，我们会详细介绍

### 更详尽错误

```rust
use std::fmt;

struct AppError {
    code: usize,
    message: String,
}

// 根据错误码显示不同的错误信息
impl fmt::Display for AppError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let err_msg = match self.code {
            404 => "Sorry, Can not find the Page!",
            _ => "Sorry, something is wrong! Please Try Again!",
        };

        write!(f, "{}", err_msg)
    }
}

impl fmt::Debug for AppError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(
            f,
            "AppError {{ code: {}, message: {} }}",
            self.code, self.message
        )
    }
}

fn produce_error() -> Result<(), AppError> {
    Err(AppError {
        code: 404,
        message: String::from("Page not found"),
    })
}

fn main() {
    match produce_error() {
        Err(e) => eprintln!("{}", e), // 抱歉，未找到指定的页面!
        _ => println!("No error"),
    }

    eprintln!("{:?}", produce_error()); // Err(AppError { code: 404, message: Page not found })

    eprintln!("{:#?}", produce_error());
    // Err(
    //     AppError { code: 404, message: Page not found }
    // )
}
```

### 错误转换`From`​特征

```rust
pub trait From<T>: Sized {
  fn from(_: T) -> Self;
}
```

自定义类型实现From特征

```rust
use std::fs::File;
use std::io;

#[derive(Debug)]
struct AppError {
    kind: String,    // 错误类型
    message: String, // 错误信息
}

// 为 AppError 实现 std::convert::From 特征，由于 From 包含在 std::prelude 中，因此可以直接简化引入。
// 实现 From<io::Error> 意味着我们可以将 io::Error 错误转换成自定义的 AppError 错误
impl From<io::Error> for AppError {
    fn from(error: io::Error) -> Self {
        AppError {
            kind: String::from("io"),
            message: error.to_string(),
        }
    }
}

fn main() -> Result<(), AppError> {
    //  ? 可以将错误进行隐式的强制转换:
    // File::open 返回的是 std::io::Error， 
    // 我们并没有进行任何显式的转换，它就能自动变成 AppError 
    let _file = File::open("nonexistent_file.txt")?;

    Ok(())
}

// --------------- 上述代码运行后输出 ---------------
Error: AppError { kind: "io", message: "No such file or directory (os error 2)" }
```

## 归一化不同的错误类型

同一函数中返回不同错误类型, 有三种方式:

* 使用特征对象 `Box<dyn Error>`​
* 自定义错误类型
* 使用 `thiserror`​

### Box<dyn Error>

```rust
use std::fs::read_to_string;
use std::error::Error;
fn main() -> Result<(), Box<dyn Error>> {
  let html = render()?;
  println!("{}", html);
  Ok(())
}

fn render() -> Result<String, Box<dyn Error>> {
  let file = std::env::var("MARKDOWN")?;
  let source = read_to_string(file)?;
  Ok(source)
}
```

* 缺陷

  * ​`Result`​ 实际上不会限制错误的类型，也就是一个类型就算不实现 `Error`​ 特征，它依然可以在 `Result<T, E>`​ 中作为 `E`​ 来使用

### 自定义错误类型

```rust
use std::fs::read_to_string;

fn main() -> Result<(), MyError> {
  let html = render()?;
  println!("{}", html);
  Ok(())
}

fn render() -> Result<String, MyError> {
  let file = std::env::var("MARKDOWN")?;
  let source = read_to_string(file)?;
  Ok(source)
}

#[derive(Debug)]
enum MyError {
  EnvironmentVariableNotFound,
  IOError(std::io::Error),
}

impl From<std::env::VarError> for MyError {
  fn from(_: std::env::VarError) -> Self {
    Self::EnvironmentVariableNotFound
  }
}

impl From<std::io::Error> for MyError {
  fn from(value: std::io::Error) -> Self {
    Self::IOError(value)
  }
}

// 为自定义错误类型实现 Error 特征后，才能转换成相应的特征对象
impl std::error::Error for MyError {}

impl std::fmt::Display for MyError {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    match self {
      MyError::EnvironmentVariableNotFound => write!(f, "Environment variable not found"),
      MyError::IOError(err) => write!(f, "IO Error: {}", err.to_string()),
    }
  }
}
```

## 简化错误处理

### thiserror

​[thiserror]()``​ 简化第二种方案

```rust
use std::fs::read_to_string;

fn main() -> Result<(), MyError> {
  let html = render()?;
  println!("{}", html);
  Ok(())
}

fn render() -> Result<String, MyError> {
  let file = std::env::var("MARKDOWN")?;
  let source = read_to_string(file)?;
  Ok(source)
}

#[derive(thiserror::Error, Debug)]
enum MyError {
  #[error("Environment variable not found")]
  EnvironmentVariableNotFound(#[from] std::env::VarError),
  #[error(transparent)]
  IOError(#[from] std::io::Error),
}
```

### error-chain 

​[error-chain]()``​ 当前不维护了

```rust
use std::fs::read_to_string;

error_chain::error_chain! {
  foreign_links {
    EnvironmentVariableNotFound(::std::env::VarError);
    IOError(::std::io::Error);
  }
}

fn main() -> Result<()> {
  let html = render()?;
  println!("{}", html);
  Ok(())
}

fn render() -> Result<String> {
  let file = std::env::var("MARKDOWN")?;
  let source = read_to_string(file)?;
  Ok(source)
}
```

### anyhow

​[anyhow]()``​ 和 `thiserror`​ 是同一个作者开发的,二者选用遵循一个原则: **是否关注自定义错误消息**，关注则使用 `thiserror`​（编写第三方库代码)，否则使用 `anyhow`​（常见业务代码)

[Comparison to anyhow](https://crates.io/crates/thiserror "Comparison to anyhow")

```rust
use std::fs::read_to_string;
use anyhow::Result;

fn main() -> Result<()> {
    let html = render()?;
    println!("{}", html);
    Ok(())
}

fn render() -> Result<String> {
    let file = std::env::var("MARKDOWN")?;
    let source = read_to_string(file)?;
    Ok(source)
}
```

‍
